name: OneTime Backend CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_VERSION: '20.x'
  AZURE_WEBAPP_NAME: 'onetime-backend'

jobs:
  # Basic checks and deployment
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --only=production

      - name: Run basic tests
        run: npm test

      - name: Check server file exists
        run: test -f server-production-minimal.js

      - name: Validate package.json
        run: node -e "console.log('Package.json is valid JSON')"

      - name: Create deployment package
        run: |
          # Remove development files
          rm -rf .git
          rm -rf node_modules
          rm -rf tests
          rm -rf .github
          # Keep only production files
          ls -la

      - name: Deploy to Azure Web App
        if: github.ref == 'refs/heads/main'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .

      - name: Success message
        run: echo "✅ Build and deployment completed successfully!"